version: '3.8'

services:
  # Back-end server 1
  back-end-1:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task6
    expose:
      - "5252"

  # Back-end server 2
  back-end-2:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task6
    expose:
      - "5252"

  # Front-end server
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task6
    expose:
      - "9000"

  # Proxy server (Nginx)
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task6
    ports:
      - "80:80"
    depends_on:
      - back-end-1
      - back-end-2
      - front-end
